// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "dhtmledit1.h"

/////////////////////////////////////////////////////////////////////////////
// CDhtmledit1

IMPLEMENT_DYNCREATE(CDhtmledit1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CDhtmledit1 properties

/////////////////////////////////////////////////////////////////////////////
// CDhtmledit1 operations
