// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "DHtmlEditOcx.h"

/////////////////////////////////////////////////////////////////////////////
// CDHtmlEditOcx

IMPLEMENT_DYNCREATE(CDHtmlEditOcx, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CDHtmlEditOcx properties

/////////////////////////////////////////////////////////////////////////////
// CDHtmlEditOcx operations
